### ISSUE TITLE
Nimble 6.0 support

### ISSUE THREAD

**Issue by AYastrebov** [RxSwiftCommunity/RxNimble#13]
Please, add the Nimble 6.0+ support
I am using cocoapods, and RxNimble force version 5.1.1 to be installed, but 6.0.1 is available already

**Comment by RafaelPlantard** [comment]
Take a look @AYastrebov

**Comment by freak4pc** [comment]
@ashfurrow Any reason this can't be merge? (Besides CI not passing at the moment)
Or at least migrate this differently?

**Comment by ashfurrow** [comment]
Yup yup, feel free to ping @RxSwiftCommunity/contributors if you ever need something 👍

**Comment by vhbit** [comment]
Fixed in v2.0
