### ISSUE TITLE
Nimble comparators seem to broken on Xcode 8.3.2 & Swift 3.1 

### ISSUE THREAD

**Issue by freak4pc** [RxSwiftCommunity/RxNimble#16]
The current code doesn't seem to catch the correct types with lhs and rhs based on the code example provided in the repo. 

![image](https://cloud.githubusercontent.com/assets/605076/25312324/29d6b0e2-281f-11e7-8161-48765bfea471.png)

I've tried messing with the code a bit and couldn't get it to work, didn't really have time to thoroughly dig into it but thought it would be good to report.

**Comment by vhbit** [comment]
Fixed in v2.0
