### ISSUE TITLE
Expectation not supporting all traits

### ISSUE THREAD

**Issue by NeverwinterMoon** [RxSwiftCommunity/RxNimble#32]
I personally ran into a problem where Single was not supported. Single is widely used for HTTP requests as we expect just a single value/error, not a stream of multiple events.

Currently, expectation confronts to `T : ObservableType`, if it would be switched to `T: ObservableConvertibleType`, it would support all observables that have `toBlocking` support.

**Comment by M0rtyMerr** [comment]
@NeverwinterMoon just met the same issue, going to open pr.
