### ISSUE TITLE
pod install fail with message "CocoaPods could not find compatible versions for pod RxNimble/RxTest"

### ISSUE THREAD

**Issue by acevif** [RxSwiftCommunity/RxNimble#37]
Hi.
Thanks for creating the nice library.

I'm in trouble now with `pod install`.

After adding a line `pod 'RxNimble/RxTest'` to Podfile, `pod install` fails with an error below:
> [!] CocoaPods could not find compatible versions for pod "RxNimble/RxTest":
>  In Podfile:
>    RxNimble/RxTest
> 
> None of your spec sources contain a spec satisfying the dependency: `RxNimble/RxTest`.
> 
> You have either:
>  * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
>  * mistyped the name or version.
>  * not added the source repo that hosts the Podspec to your Podfile.
> 
> Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.
> ❌️ ERROR 31

How can I fix it?

Thanks in advance.

**Comment by fernandocruz** [comment]
Same here :/

**Comment by gobetti** [comment]
Looks like the last available version in the CocoaPods master repo is still 4.2.0: https://cocoapods.org/pods/RxNimble

@ashfurrow or anyone, how have you been managing `pod trunk push`? Could someone please push 4.4.0? Thanks!

@acevif @fernandocruz until then you can install the pod by manually referencing the repository:
`pod 'RxNimble/RxTest', :git => 'https://github.com/RxSwiftCommunity/RxNimble.git'`

**Comment by ashfurrow** [comment]
Ah, yeah 4.4.0 was never related. I'll do that now.

**Comment by ashfurrow** [comment]
I tried pushing this but it failed to compile. @gobetti I made this change to fix it: https://github.com/RxSwiftCommunity/RxNimble/commit/a4d5f90fd25df3777c6f03707776d7e0f6d1743c Looks like we were only using that one struct, so I just copied it. I'll let you know how the new push goes.

**Comment by ashfurrow** [comment]
Okay, I can't get this to pass. Can someone else try running this on their machine?

```
pod lib lint --allow-warnings
```

I keep getting this error:

```
 -> RxNimble (4.4.0)
    - ERROR | [RxNimble/Core,RxNimble/RxBlocking] xcodebuild: Returned an unsuccessful exit code.
    - NOTE  | [RxNimble/Core, RxNimble/RxBlocking, RxNimble/RxTest, and more...] xcodebuild:  note: Using new build system
    - NOTE  | [RxNimble/Core, RxNimble/RxBlocking, RxNimble/RxTest, and more...] xcodebuild:  note: Planning build
    - NOTE  | [RxNimble/Core, RxNimble/RxBlocking, RxNimble/RxTest, and more...] xcodebuild:  note: Constructing build description
    - NOTE  | [RxNimble/Core, RxNimble/RxBlocking, RxNimble/RxTest, and more...] xcodebuild:  warning: Skipping code signing because the target does not have an Info.plist file. (in target 'App')
    - NOTE  | [iOS] xcodebuild:  error:
    - NOTE  | [tvOS] xcodebuild:  clang: error:
    - NOTE  | [RxNimble/Core,RxNimble/RxBlocking] xcodebuild:  clang: error: linker command failed with exit code 1 (use -v to see invocation)
    - NOTE  | [RxNimble/Core,RxNimble/RxBlocking] xcodebuild:  error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by gobetti** [comment]
ah sorry for that @testable thing, it built fine for me and also when building with Carthage in the carthage PR :/

I can check this tomorrow, but just for sanity check, pod lib lint is fine in your machine if you try it at the 4.3.0 tag? (that version happens to be unreleased as well)

**Comment by ashfurrow** [comment]
No worries! Okay, looks like something was up, but I fixed the linker error but explicitly requiring `XCTest`. Not sure how this was working before, but it's working now! I've released 4.4.0 to CocoaPods, let me know how it goes 👍

**Comment by ashfurrow** [comment]
The commit is here btw: https://github.com/RxSwiftCommunity/RxNimble/commit/bb17e404067f5132b2f67c93fb485454415a8bcc

**Comment by acevif** [comment]
Thanks, @ashfurrow @gobetti!
Now `pod install` succeeds for me!
I close this issue now.
Thanks a lot.

@fernandocruz Please reopen this issue in case it doesn't work fine for you.
