### ISSUE TITLE
Remove equalFirst

### ISSUE THREAD

**Issue by M0rtyMerr** [RxSwiftCommunity/RxNimble#46]
These methods were deprecated in 2017/11/02. I think two years are more than enough to migrate codebase (especially for such small repo). What do you think about removing them with version bump? Just to prevent potential user confusion.

**Comment by ashfurrow** [comment]
Yeah, that makes sense to me. Let's include a `**Break Change**` line to the changelog, and include migration steps as well. We'll still need to do a major release with these changes (in this case, `4.5.0` -> `5.0.0`) so we should see if there are any other breaking changes we want to include 😉

**Comment by M0rtyMerr** [comment]
Ok, i will submit PR

**Comment by M0rtyMerr** [comment]
Resolved
