### ISSUE TITLE
Auto linking library fails with Swift version 5.2

### ISSUE THREAD

**Issue by BastianKusserow** [RxSwiftCommunity/RxNimble#53]
I just tried to check out and build the project with Swift version 5.2 and got the error message 
```
Could not find or use auto-linked library 'XCTest'
Could not find or use auto-linked library 'XCTestSupport'
```
When I explicitly link the XCTest framework into the project, it works just fine, but I cannot build my project when using this library with carthage.

**Comment by ashfurrow** [comment]
Gotcha, sounds like a problem we can fix. I'm not a Carthage user, so maybe you could take a look and send a pull request?
