### ISSUE TITLE
Xcode 15 Nimble & Foundation naming conflict 

### ISSUE THREAD

**Issue by N1nomiya** [RxSwiftCommunity/RxNimble#69]
Hi, when using Xcode 15, RxNimble has an error _'Predicate' is ambiguous for type lookup in this context_ since Foundation has a conflict type `Predicate` with Nimble. 
This is the related [issue link](https://github.com/Quick/Nimble/issues/1061) in Nimble. I think maybe you want to consider the workaround described in it.

**Comment by younata** [comment]
Hi! As the maintainer of Nimble, I want to jump in and note that as part of addressing this name conflict, I'm planning to rename the `Predicate` API to `Matcher`. https://github.com/Quick/Nimble/pull/1090 has more details about that.

**Comment by dzolnai** [comment]
Hello, assuming you are releasing Nimble today (according to https://github.com/Quick/Nimble/issues/1061#issuecomment-1745325472), could you make a new version of this library as well?
Thanks for the library in any case! 🙌

**Comment by ashfurrow** [comment]
@dzolnai we're just looking for an update to this library that points to the new Nimble version, yeah? I tried getting this to pass CocoaPods validation but ran into some of those predicate errors: https://github.com/RxSwiftCommunity/RxNimble/pull/70 Any tips?

**Comment by dzolnai** [comment]
@ashfurrow it seems that it doesn't take the deployment target from the spec file. I can reproduce it locally, but have no idea how it could be fixed.

Yes I just need the new Nimble version, because right now our tests do not run on Xcode 15.

**Comment by dzolnai** [comment]
I think we are running into this issue: https://github.com/CocoaPods/CocoaPods/issues/11839

**Comment by ashfurrow** [comment]
Ah fun fun. Okay. So this should work with Xcode 14.2 for now? I can download that and use it to publish the new version. 

(Fixing this bug in a PR, as Orta mentioned in that thread, would be a great too. But I want to unblock you all first.)

**Comment by mgray88** [comment]
The only pod spec lint errors I got for #70 were related to `Predicate` :thinking:

edit:
environment:
```
xcode-select -p
/Applications/Xcode-15.0.0.app/Contents/Developer

swift --version
swift-driver version: 1.87.1 Apple Swift version 5.9 (swiftlang-5.9.0.128.108 clang-1500.0.40.1)
Target: x86_64-apple-macosx13.0

pod --version
1.12.1
```

**Comment by dzolnai** [comment]
Yes but once you fix those, you will get a hidden DT_TOOLCHAIN error, which then suggests that you upgrade to Pod 1.13.0. And when you do, the same errors will appear (at least, that's what happened to me) as in the top post.

But yes, Predicate needs to be replaced with Matcher in the sources first.

**Comment by ashfurrow** [comment]
I've released a new version in #70 for the latest version of Nimble, 6.3.0 of RxNimble. Let me know 👍

**Comment by ashfurrow** [comment]
Oh, and Xcode 14.2 did work.

**Comment by ashfurrow** [comment]
Thanks to @N1nomiya in #71, I've released 6.3.1 of RxNimble that _should_ fix this. Could someone verify and let us know?

**Comment by dzolnai** [comment]
Thanks, for us it works as expected now.

I did see the following error when updating:
> Specs satisfying the `RxNimble (= 6.3.1)` dependency were found, but they required a higher minimum deployment target.

I just had to update my first line in the Podfile to:
`platform :ios, '13.0'`

(We were already using 13.0 as the minimum deployment target for our apps, but that was set in Xcode, not in the Podfile)

**Comment by N1nomiya** [comment]
Thanks @dzolnai , 6.3.1 works for me in Xcode 15 as well.
I think this issue is ready to close. Thank you all 🙌
