### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by siejkowski** [RxSwiftCommunity/RxNimble#9]
Is the lack of Carthage support a design decision or just no one got to do it yet? 😊

**Comment by gperdomor** [comment]
i need this too

**Comment by palusik86** [comment]
same here ;-)

**Comment by mingchen** [comment]
I have a pull request https://github.com/RxSwiftCommunity/RxNimble/pull/24 try to fix this issue.
Before it get merged, you can add following line to Cartfile as a temporal solution.
  
    github "mingchen/RxNimble" "master"
